# Generated by Django 5.2.5 on 2025-09-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_remove_zone_available_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_nodes', to='parkinglot.floor')),
                ('slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_node', to='parkinglot.carslot')),
            ],
        ),
        migrations.CreateModel(
            name='MapEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=1.0)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_end', to='parkinglot.mapnode')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_start', to='parkinglot.mapnode')),
            ],
        ),
    ]
