# Generated by Django 5.2.5 on 2025-09-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_mapnode_mapedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapedge',
            name='direction',
            field=models.CharField(choices=[('straight', 'Đi thẳng'), ('left', 'Rẽ trái'), ('right', 'Rẽ phải'), ('elevator', 'Đi thang máy'), ('ramp', 'Đi theo dốc'), ('destination', 'Đến vị trí')], default='straight', max_length=20),
        ),
        migrations.AddField(
            model_name='mapnode',
            name='is_gate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mapedge',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='parkinglot.mapnode'),
        ),
        migrations.AlterField(
            model_name='mapedge',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='parkinglot.mapnode'),
        ),
        migrations.AlterField(
            model_name='mapnode',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_nodes', to='parkinglot.floor'),
        ),
    ]
