# Generated by Django 5.2.5 on 2025-09-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0004_mapedge_direction_mapnode_is_gate_alter_mapedge_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carslot',
            name='x1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carslot',
            name='x2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carslot',
            name='y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carslot',
            name='y2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
