# Generated by Django 5.2.5 on 2025-09-11 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0005_carslot_x1_carslot_x2_carslot_y1_carslot_y2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carslot',
            name='map_x',
        ),
        migrations.RemoveField(
            model_name='carslot',
            name='map_y',
        ),
    ]
