# Generated by Django 5.2.5 on 2025-09-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0006_remove_carslot_map_x_remove_carslot_map_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapnode',
            name='node_type',
            field=models.CharField(choices=[('gate', 'Cổng chính'), ('elevator', 'Thang máy'), ('road', 'Đường đi'), ('slot', 'Chỗ đậu xe')], default='slot', max_length=20),
        ),
    ]
