# Generated by Django 5.2.5 on 2025-08-18 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('package_type', models.CharField(choices=[('monthly', 'Theo tháng'), ('weekly', 'Theo tuần'), ('custom', 'Chọn ngày')], max_length=10)),
                ('selected_days', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('online', 'Online'), ('on_exit', 'Thanh toán khi lấy xe')], max_length=10)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('car_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parkinglot.carslot')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.floor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
