# Generated by Django 5.2.5 on 2025-08-18 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_app', '0001_initial'),
        ('parkinglot', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.vehicle'),
        ),
        migrations.AddField(
            model_name='booking',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkinglot.zone'),
        ),
    ]
