# Generated by Django 5.2.5 on 2025-08-19 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_initial'),
        ('parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='selected_days',
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='parkinglot.carslot'),
        ),
    ]
