# Generated by Django 5.2.5 on 2025-08-21 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_remove_booking_selected_days_alter_booking_car_slot'),
        ('parkinglot', '0002_remove_zone_available_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_checked_in',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_checked_out',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_status',
            field=models.CharField(choices=[('checked_in', 'Đã check-in'), ('not_checked_in', 'Chưa check-in'), ('checked_out', 'Đã check-out')], default='not_checked_in', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chưa thanh toán'), ('completed', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parkinglot.zone'),
        ),
    ]
