# Generated by Django 5.2.5 on 2025-08-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_packagepricing_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepricing',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Xe Oto'), ('Motorbike', 'Xe Máy')], default='Car', max_length=20),
        ),
    ]
