# Generated by Django 5.2.5 on 2025-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_packagepricing_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Online'), ('on_exit', 'Thanh toán khi lấy xe')], default='online', max_length=10),
        ),
    ]
