# Generated by Django 5.2.5 on 2025-09-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_alter_booking_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_status',
            field=models.CharField(choices=[('checked_in', 'Đã check-in'), ('not_checked_in', 'Chưa check-in'), ('checked_out', 'Đã check-out'), ('parked', 'Đã đậu vào chỗ đậu xe')], default='not_checked_in', max_length=20),
        ),
    ]
